# Parameters

In [38]:
show_intermediate_results = True

# Preparations

## Imports

In [ ]:
import polars as pl

playlists = pl.scan_parquet('../processed_data/data_playlist_metadata.parquet')

## Playlist Source Data

In [ ]:
playlists.collect(engine='streaming')

shape: (86_276, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ playlist. ┆ playlist. ┆ owner.id  ┆ owner.nam ┆ … ┆ playlist. ┆ owner.is_ ┆ song_coun ┆ artist_c │
│ id        ┆ name      ┆ ---       ┆ e         ┆   ┆ is_social ┆ wcs_dj    ┆ t         ┆ ount     │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ _set      ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆           ┆ str       ┆   ┆ ---       ┆ bool      ┆ u32       ┆ u32      │
│           ┆           ┆           ┆           ┆   ┆ bool      ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 000PP6yV3 ┆ Joensuu   ┆ mjannis   ┆ Jannis    ┆ … ┆ false     ┆ false     ┆ 45        ┆ 42       │
│ 2HhGWZ8Nk ┆           ┆           ┆ Makropulo ┆   ┆           ┆           ┆           ┆          │
│ D7Jd      ┆           ┆           ┆ s         ┆   ┆           ┆           ┆           ┆          │
│ 000QVDaEe ┆ Songs     ┆ wcsdunedi ┆ WCSMelbou ┆ … ┆ false     ┆ false     ┆ 397       ┆ 327      │
│ EmfVJpfdd ┆ with Swin ┆ n         ┆ rne       ┆   ┆           ┆           ┆           ┆          │
│ p611      ┆ g/Blues   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Shuffle…  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 000hjS5mH ┆ WSNW '25  ┆ 118542800 ┆ Kasia     ┆ … ┆ false     ┆ true      ┆ 26        ┆ 25       │
│ vPqB6B9kD ┆ Saturday  ┆ 2         ┆ Stepek    ┆   ┆           ┆           ┆           ┆          │
│ 46zc      ┆ 03:00     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 001F19s2D ┆ SAT,      ┆ angelabeh ┆ angelabeh ┆ … ┆ false     ┆ false     ┆ 12        ┆ 12       │
│ 2jzePZL6k ┆ 4-DEC     ┆ nken      ┆ nken      ┆   ┆           ┆           ┆           ┆          │
│ mqYM      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 001eKsoK3 ┆ 🌾🌄      ┆ amrosso22 ┆ Aubrey    ┆ … ┆ false     ┆ false     ┆ 36        ┆ 17       │
│ IlnY35gLu ┆           ┆           ┆ Rosso     ┆   ┆           ┆           ┆           ┆          │
│ LgaC      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 7zxTNmWpB ┆ old pop   ┆ 118542800 ┆ Kasia     ┆ … ┆ false     ┆ true      ┆ 55        ┆ 47       │
│ gXQAYpVdp ┆           ┆ 2         ┆ Stepek    ┆   ┆           ┆           ┆           ┆          │
│ qf0i      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7zy99M6oT ┆ old pop   ┆ 118542800 ┆ Kasia     ┆ … ┆ false     ┆ true      ┆ 86        ┆ 69       │
│ hI8U6AqiQ ┆           ┆ 2         ┆ Stepek    ┆   ┆           ┆           ┆           ┆          │
│ soru      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7zyfGCIIB ┆ Mel's     ┆ 127292484 ┆ Melissa   ┆ … ┆ false     ┆ false     ┆ 60        ┆ 53       │
│ fSpHGPMGe ┆ Teaching  ┆ 1         ┆ Oh Yay    ┆   ┆           ┆           ┆           ┆          │
│ CP8l      ┆ WCS Blues ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Playl…    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7zz3LspiA ┆ WCS Slow  ┆ fongyewin ┆ Yewin     ┆ … ┆ false     ┆ false     ┆ 1         ┆ 1        │
│ 3RecgBUt8 ┆           ┆           ┆ Fong      ┆   ┆           ┆           ┆           ┆          │
│ Ty2E      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ new_1STEV ┆ HH klimat ┆ 21v7353yk ┆ Adam Jask ┆ … ┆ false     ┆ false     ┆ 2373      ┆ 1595     │
│ aw1av8Fp9 ┆           ┆ ueuavmw7e ┆ iernik    ┆   ┆           ┆           ┆           ┆          │
│ LtAzQMdt  ┆           ┆ yvvbfxa   ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Analysis

Step 1: Tokenize the playlist names by splitting on whitespaces.

We currently turn every word into its own separate keyword term.
As a later optimization, it might make sense to treat words most often
occuring together (e.g. `late night`) to make the output more useful.

In [41]:
playlists_tokenized = playlists.select(
    pl.col('playlist.id'),
    pl.col('playlist.name'),
    pl.col('playlist.name').str.to_lowercase().str.split(' ')
    .list.filter(pl.element().ne(''))
    .list.unique(maintain_order=True).alias('unique_terms'),
)

playlists_tokenized.collect(engine='streaming') if show_intermediate_results else None

shape: (86_276, 3)
┌────────────────────────────┬─────────────────────────────────┬─────────────────────────────────┐
│ playlist.id                ┆ playlist.name                   ┆ unique_terms                    │
│ ---                        ┆ ---                             ┆ ---                             │
│ str                        ┆ str                             ┆ list[str]                       │
╞════════════════════════════╪═════════════════════════════════╪═════════════════════════════════╡
│ 000PP6yV32HhGWZ8NkD7Jd     ┆ Joensuu                         ┆ ["joensuu"]                     │
│ 000QVDaEeEmfVJpfddp611     ┆ Songs with Swing/Blues Shuffle… ┆ ["songs", "with", … "timing"]   │
│ 000hjS5mHvPqB6B9kD46zc     ┆ WSNW '25 Saturday 03:00         ┆ ["wsnw", "'25", … "03:00"]      │
│ 001F19s2D2jzePZL6kmqYM     ┆ SAT, 4-DEC                      ┆ ["sat,", "4-dec"]               │
│ 001eKsoK3IlnY35gLuLgaC     ┆ 🌾🌄                            ┆ ["🌾🌄"]                        │
│ …                          ┆ …                               ┆ …                               │
│ 7zxTNmWpBgXQAYpVdpqf0i     ┆ old pop                         ┆ ["old", "pop"]                  │
│ 7zy99M6oThI8U6AqiQsoru     ┆ old pop                         ┆ ["old", "pop"]                  │
│ 7zyfGCIIBfSpHGPMGeCP8l     ┆ Mel's Teaching WCS Blues Playl… ┆ ["mel's", "teaching", … "playl… │
│ 7zz3LspiA3RecgBUt8Ty2E     ┆ WCS Slow                        ┆ ["wcs", "slow"]                 │
│ new_1STEVaw1av8Fp9LtAzQMdt ┆ HH klimat                       ┆ ["hh", "klimat"]                │
└────────────────────────────┴─────────────────────────────────┴─────────────────────────────────┘

Step 2: Aggregate over playlist terms

In [ ]:
exploded_playlists_tokenized = playlists_tokenized\
    .explode('unique_terms')\
    .rename({'unique_terms': 'term'})

exploded_playlists_tokenized.limit(100).collect(engine='streaming') if show_intermediate_results else None

shape: (100, 3)
┌────────────────────────┬─────────────────────────────────┬─────────────┐
│ playlist.id            ┆ playlist.name                   ┆ term        │
│ ---                    ┆ ---                             ┆ ---         │
│ str                    ┆ str                             ┆ str         │
╞════════════════════════╪═════════════════════════════════╪═════════════╡
│ 000PP6yV32HhGWZ8NkD7Jd ┆ Joensuu                         ┆ joensuu     │
│ 000QVDaEeEmfVJpfddp611 ┆ Songs with Swing/Blues Shuffle… ┆ songs       │
│ 000QVDaEeEmfVJpfddp611 ┆ Songs with Swing/Blues Shuffle… ┆ with        │
│ 000QVDaEeEmfVJpfddp611 ┆ Songs with Swing/Blues Shuffle… ┆ swing/blues │
│ 000QVDaEeEmfVJpfddp611 ┆ Songs with Swing/Blues Shuffle… ┆ shuffle     │
│ …                      ┆ …                               ┆ …           │
│ 00BrxSphwuS0d6xb4iI0b5 ┆ Best WCS by BPM Old             ┆ wcs         │
│ 00BrxSphwuS0d6xb4iI0b5 ┆ Best WCS by BPM Old             ┆ by          │
│ 00BrxSphwuS0d6xb4iI0b5 ┆ Best WCS by BPM Old             ┆ bpm         │
│ 00BrxSphwuS0d6xb4iI0b5 ┆ Best WCS by BPM Old             ┆ old         │
│ 00ButGQ0DzNLgPa4eyOsnC ┆ My Shazam Tracks                ┆ my          │
└────────────────────────┴─────────────────────────────────┴─────────────┘

In [34]:
tokens = exploded_playlists_tokenized\
    .group_by('term')\
    .agg(pl.col('term').count().alias('playlist_count'))\
    .sort('playlist_count', descending=True)

Review query plan for potential performance/memory problems:

In [ ]:
tokens.show_graph(plan_stage='physical', engine='streaming', optimized=True)

In [46]:
tokens.filter(pl.col('playlist_count').ge(100)).collect(engine='streaming')

shape: (265, 2)
┌────────┬────────────────┐
│ term   ┆ playlist_count │
│ ---    ┆ ---            │
│ str    ┆ u32            │
╞════════╪════════════════╡
│ wcs    ┆ 14539          │
│ -      ┆ 6276           │
│ swing  ┆ 2652           │
│ blues  ┆ 1961           │
│ bpm    ┆ 1957           │
│ …      ┆ …              │
│ finals ┆ 102            │
│ mar    ┆ 102            │
│ cool   ┆ 102            │
│ 120    ┆ 101            │
│ faves  ┆ 100            │
└────────┴────────────────┘